### ISSUE TITLE
Errors Inconsistent

### ISSUE THREAD

**Issue by KarlKeat** [biologyguy/BuddySuite#1]
When inputting a file with an incorrect alphabet (Protein file in a method designed for DNA, etc), some methods throw a TypeError, others an AttributeError, and rarely a ValueError. They should all be ValueErrors.

**Comment by biologyguy** [comment]
Changed a bunch of the Error types to be more representative of what's actually going wrong. ValueError doesn't always make the most sense (in fact, TypeError makes more sense in most places).
