### ISSUE TITLE
problem with deleting invariant sites

### ISSUE THREAD

**Issue by thkuo** [biologyguy/BuddySuite#114]
Dear developers,

I was trying to delete invariant sites in my alignment but just found that the alignbuddy I installed seems not include the option (--delete_invariant_sites). It was installed yesterday with pip. Can I know any possible solution?

**Comment by KarlKeat** [comment]
Hello,

This feature is not available in the current stable release of BuddySuite (1.2.7). It is slated to be released in version 1.3. However, if you would like to try it out now, you may clone this repository and check-out the "develop" branch.

Thank you for using BuddySuite!
