### ISSUE TITLE
Add tutorials to documentation

### ISSUE THREAD

**Issue by etiology** [biologyguy/BuddySuite#12]
This is such a great tool that needs examples of use.  I would love to see a few short pipeline examples in a tutorial section  of the documentation.  

The demo last night using uniprot accession ids to pull down data and manipulate it was great.  Ideally it would be nice to have a hand full of use case examples for each of the four tools:
- **SeqBuddy**
- **AlignBuddy**
- **DBBuddy**
- **PhyloBuddy**

Please post suggestions of short examples to this issue

**Comment by biologyguy** [comment]
A complete walk through of an end-to-end example is now available in the [Tutorial](https://github.com/biologyguy/BuddySuite/wiki/Tutorial)
