### ISSUE TITLE
AlignBuddy in multiple cores

### ISSUE THREAD

**Issue by amartinezgarcia** [biologyguy/BuddySuite#126]
Hi! Thanks a lot for this fantastic set of tools! 
I am running AlignBuddy on quite large alignments using a MacOS Sierra. Is there any way to run it on multiple cores?  
Best!
Alejandro

**Comment by biologyguy** [comment]
Hi Alejandro,
It depends on what tools you are using. Give me an example command and I'll let you know what I think.
-Steve

**Comment by biologyguy** [comment]
Closing because no reply

**Comment by amartinezgarcia** [comment]
Dear Steve,
I didnt see you message! Sorry! I am using mostly muscle:

alb data.fas -ga muscle > data.ali.fas

Thanks for the answer!

**Comment by biologyguy** [comment]
Ha, no worries :)
So, in your case, AlignBuddy is simply wrapping the alignment program muscle. I believe MUSCLE is serial, so there's not much you can do to speed it up. Maybe MAFFT? 

```
$: alignbuddy data.fas -ga mafft " --thread 8"
```

**Comment by amartinezgarcia** [comment]
Thanks a lot!!
