### ISSUE TITLE
"FTP Error: got more than 8192 bytes"

### ISSUE THREAD

**Issue by dougwyu** [biologyguy/BuddySuite#127]
`seqbuddy example.fa --clean_seq > example_clean.fa`

"FTP Error: got more than 8192 bytes" is appended to end of fasta file

`example.fa`

> \>Acanthis_flammea_KR422696
> aaacaaaacctccaaaaattagaccaaacctctagactgagagcaacccctcaacgtgct
> aatagcatccagacccaatataattgatcaatggacca
> \>Acanthisitta_chloris_AY325307
> aaaaacaaaacctccagaactaggaccacccctcttaacccagagcaacccctcaacgta
> ctaacagtaaccagacccaataacattgaccaatggacca
> \>Acanthiza_nana_KY994614
> caaatcctccgaaaaccagaccataactcttgaccaagagcaacccctcgacgtgctaat
> agcatccagacccaatataattgagcaatggacca
> \>Acanthophis_praelongus_EU547161
> aaaaaaagaacttccaaacacataatctaaaattacccactcaggccgacaagcctacaa
> cgacccagcatagctgacaattgaacca
> 

`example_clean.fa`

> \>Acanthis_flammea_KR422696
> aaacaaaacctccaaaaattagaccaaacctctagactgagagcaacccctcaacgtgct
> aatagcatccagacccaatataattgatcaatggacca
> \>Acanthisitta_chloris_AY325307
> aaaaacaaaacctccagaactaggaccacccctcttaacccagagcaacccctcaacgta
> ctaacagtaaccagacccaataacattgaccaatggacca
> \>Acanthiza_nana_KY994614
> caaatcctccgaaaaccagaccataactcttgaccaagagcaacccctcgacgtgctaat
> agcatccagacccaatataattgagcaatggacca
> \>Acanthophis_praelongus_EU547161
> aaaaaaagaacttccaaacacataatctaaaattacccactcaggccgacaagcctacaa
> cgacccagcatagctgacaattgaacca
> FTP Error: got more than 8192 bytes

**Comment by biologyguy** [comment]
Unable to reproduce
