### ISSUE TITLE
Error on Anaconda Environment Install: ModuleNotFoundError: No module named 'buddy_resources'

### ISSUE THREAD

**Issue by john-k-boyd** [biologyguy/BuddySuite#128]
Can't seem to get past this error:

ModuleNotFoundError: No module named 'buddy_resources'

**Comment by biologyguy** [comment]
How'd you do the install? pip? setup.py?

**Comment by ChemJY** [comment]
I got the same issue, I installed by pip

**Comment by biologyguy** [comment]
Ah, I see. Biopython update has busted things. I will need to find some time to try and resolve this.

**Comment by jeffreykstone** [comment]
Any luck on resolving this? I am having the same issue on my Mac.

**Comment by biologyguy** [comment]
Year and a half later and probably of no use to any involved in this thread, but I've created a new release. BuddySuite should run again (mostly).
