### ISSUE TITLE
Add Continuous Integration tool to the repo

### ISSUE THREAD

**Issue by etiology** [biologyguy/BuddySuite#13]
Continuous integration tools like [TravisCI](https://travis-ci.org/getting_started) would help keep the codebase clean and stable.  It detects when a commit is made and pushed and it builds and tests the code.  This is a great way to ensure that only tested code is getting integrated.

**Comment by biologyguy** [comment]
This is seriously under way, thanks to Dustin.

**Comment by biologyguy** [comment]
Up and running! Closing out.
