### ISSUE TITLE
Add logging to toolsets

### ISSUE THREAD

**Issue by etiology** [biologyguy/BuddySuite#14]
Adding logging to the various tools would improve troubleshooting and make it easier to address issues.  Given that this toolset needs to adhere to strict privacy rules, we should also have some guidelines on logging policy.

**Comment by biologyguy** [comment]
Given that the toolkits are not being run as persistent services and there is a mechanism for sending tracebacks when things crash, I think that continuous logging to the users computer is overkill. Perhaps better to dump more info about the state of variables upon crash, and bundle that into the traceback? The issue of PII could come into play here, though.

**Comment by jwbowen** [comment]
So close this one?
