### ISSUE TITLE
Break up large modules into smaller ones in a package

### ISSUE THREAD

**Issue by etiology** [biologyguy/BuddySuite#15]
Some of the files are 1-2 thousand lines long but could be broken up to make future development easier.  I tend to like breaking long modules up and placing them into a package.  We can then use the __init__.py file to import the individual pieces.  As a result this usually doesn't require changing any external code since using the __init__.py file connects the pieces together.

**Comment by biologyguy** [comment]
Adding this to wish list for V 1.3 (issue #68)
