### ISSUE TITLE
Need Stats on file size(s) used

### ISSUE THREAD

**Issue by etiology** [biologyguy/BuddySuite#16]
This may be related to #14 

Getting information on what size of files are being used and the file types would be really helpful for future dev.  Also the types of files that are being run with these tools would be nice to know.  

This may be something that goes into both logging and reporting

**Comment by biologyguy** [comment]
Rough files sizes are now appended to usage stats.
Closed with commit a7770ce1bcfd02aa5d5af9f570692e60b8383bb5
