### ISSUE TITLE
Need to rename packages, modules, and classes (PEP8)

### ISSUE THREAD

**Issue by etiology** [biologyguy/BuddySuite#22]
The naming of project files should follow [pep8](https://www.python.org/dev/peps/pep-0008/#descriptive-naming-styles) recommendations.  This will improve code clarity

**Comment by biologyguy** [comment]
@etiology 
Hey Todd,
Unless you have further suggestions here, I'm going to close out this issue.

**Comment by etiology** [comment]
At the moment I don't have any work on this issue so feel free to close it.  This issue could turn into a very large refactor and I haven't been able to invest in it. 

You have my vote to close it
