### ISSUE TITLE
test suites need to be reorganized

### ISSUE THREAD

**Issue by etiology** [biologyguy/BuddySuite#23]
The current test files are mixed into the main workshop package.  All tests need to be localized into their own 'tests' package.  Fixtures and helper functions need to be pulled into their own configtest file.

**Comment by jwbowen** [comment]
Can this issue be closed now?

**Comment by biologyguy** [comment]
Resolved with commit e9020ac6403d72a5a7b9e6fda6f91e3f3f57b6ba
