### ISSUE TITLE
External Dependency List

### ISSUE THREAD

**Issue by etiology** [biologyguy/BuddySuite#28]
Please leave any external dependencies in this issue.  We need to document these in some way.
  - **[mafft](http://mafft.cbrc.jp/alignment/software/)**
  - **[prank](http://wasabiapp.org/software/prank/prank_installation/)**
  - **[pagan](http://wasabiapp.org/software/pagan/pagan_installation/)**
  - **[muscle](http://www.drive5.com/muscle/downloads.htm)**
  - **[clustalw](http://www.clustal.org/clustal2/#Download)**
  - **[clustalw2](http://www.clustal.org/clustal2/#Download)**
  - **[clustalomega](http://www.clustal.org/omega/#Download)**
  - **[clustalo](http://www.clustal.org/omega/#Download)**
  - **blast+**

**Comment by jwbowen** [comment]
The wiki pages look great!
