### ISSUE TITLE
How many other's peoples software do we want to unit test

### ISSUE THREAD

**Issue by biologyguy** [biologyguy/BuddySuite#40]
Probably want to change the way tests are handled to separate out the logic of BuddySuite and the actual output of third party software. That way if I break something I'll know it was me, and not the 3rd party.
For example, different versions of RAxML are outputing slightly different branch lengths.

**Comment by etiology** [comment]
We could certainly test the call syntax and mock out the actual system call. Would be faster to test. 

Ideally tests shouldn't take long to run. We should be running them often during dev.

**Comment by biologyguy** [comment]
This is largely resolved now by including specific 3rd party tests for each buddy module.
