### ISSUE TITLE
Dump the sequence files from failed hash tests to file

### ISSUE THREAD

**Issue by biologyguy** [biologyguy/BuddySuite#43]
Because of the hashing paradigm used for the unit tests, troubleshooting failures usually requires that each failed tests needs to be isolated and printed out. It would be nice if failed tests wrote to a file with the given hash as it's name. Include the entire contents of the output being converted to the MD5 hash (i.e., running md5 on the file should return the same hash as the file name).
Not 100% sure how to implement this yet. Fixture?

**Comment by etiology** [comment]
Well in the very least we can add the optional assert message to provide more informative failures when tests run.  [Here](https://wiki.python.org/moin/UsingAssertionsEffectively) is an example: 
``` python
assert received_hash == expected_hash, "Hash output failure.  Expected '{expected}' but received '{received}'".format(expected=expected_hash, received=received_hash)
```

I will sometimes toss some newlines in that string to give that output string some space.  It makes it easier to find.

**Comment by biologyguy** [comment]
Awesome, this works

```python
def test_clean_seqs():
    tester = Alb.clean_seq(Alb.AlignBuddy(resource("ambiguous_dna_alignment.fa")), ambiguous=False, rep_char="X")
    test_hash = align_to_hash(tester)
    assert test_hash == "6755ea1408eddd0e5f267349c287d989", tester.write("error_files/%s" % test_hash)
```
Files are only written on failure!

**Comment by biologyguy** [comment]
This method works well, so closing out the issue
