### ISSUE TITLE
count_residues estimates frequency '-'. add clean?

### ISSUE THREAD

**Issue by mendessoares** [biologyguy/BuddySuite#46]
If the sequences in the file are not clean, it will return frequency of '-'. It would also be useful to have an option to clean the sequence to get rid of these.

**Comment by etiology** [comment]
That's a good catch.

**Comment by biologyguy** [comment]
@mendessoares are you interested in implementing this? It's a very good idea, and should be straight forward to include.

**Comment by mendessoares** [comment]
Sure


-------- Original message --------

**Comment by KarlKeat** [comment]
Resolved with commit 8810f91
