### ISSUE TITLE
Use Distutils/setuptools and make the installation process more inline with common Python practice

### ISSUE THREAD

**Issue by jwbowen** [biologyguy/BuddySuite#47]
The current installation process relies on editing a user's .profile and creating a hidden directory under the user's home directory, which is added to the user's PATH environment variable.

The installer bundles Biopython, DendroPy, the ETE toolkit, and BLAST into a binary file (which is named with a .py extension, despite being binary data) for installation. While this simplifies installation, it produces a 22 MB binary file.

Ideally the installation would use Distutils/setuptools and a setup.py file and/or pip to install the package.

**Comment by biologyguy** [comment]
This is working after commit 8839e71795a443d18f630736e662a4ee496e785a
I'll open a new issue to cover the installation and maintenance of a BuddySuite .conf file and a usage tracker, which were collateral damage from the migration to setuptools.
