### ISSUE TITLE
Reorganize repo to be more in line with common Python practice

### ISSUE THREAD

**Issue by jwbowen** [biologyguy/BuddySuite#48]
It would be nice if the directory layout of the repo were brought into line with common Python practices (browse other Python projects on GitHub to get a feel for this).

**Comment by biologyguy** [comment]
Do you think things look tidier now? Close the ticket out?

**Comment by jwbowen** [comment]
For the most part. @etiology can comment as well, but I would also like to see all of the tests under .../buddysuite/test before closing this one.

**Comment by etiology** [comment]
Agreed.  I think we still have one more test file to move.  I could see us breaking each Buddy element into  their own package.  I don't know if this would qualify for this issue but it would be nice to get those modules into a less fragile state.

**Comment by etiology** [comment]
It is looking much better though.  Good job on the cleanup

**Comment by jwbowen** [comment]
I think this issue can be closed now.
