### ISSUE TITLE
Test Fixtures need to be cleaned up

### ISSUE THREAD

**Issue by etiology** [biologyguy/BuddySuite#55]
Text fixtures appear to be trying to do too much.  The fixture functions should be a short setup of a fixture.  This makes it easy to maintain and understand.  Some of the fixtures are [defining their own classes before deploying them](https://github.com/biologyguy/BuddySuite/blob/f7fe13f68affce3f31350e5862512599f44f2b81/buddysuite/tests/conftest.py#L19-L97).

This class definitions doesn't belong in the fixture setup.  What if we moved it to the test package ```__init__.py``` file?

**Comment by biologyguy** [comment]
I'm open to any suggestions, as long as I retain all of the functionality I need for managing resources by those little letter codes.

**Comment by biologyguy** [comment]
Copied Todd's solution for remaining untidy fixtures.
Commit 7beb62f0bd74029af4f50be63bfb76768b9df360
