### ISSUE TITLE
Reimplement .conf file and usage tracking

### ISSUE THREAD

**Issue by biologyguy** [biologyguy/BuddySuite#58]
The migration over to setuptools for installation wiped out the configuration file, usage tracking file, and TopCons job ids dir, which were originally stored in ~/.buddysuite.
These need to be reimplemented somehow, in line with the new installation location (probably in site-packages?).

**Comment by jwbowen** [comment]
For Linux, storing it under `~/.buddysuite` would actually be the preferred location. Would it be the same for OSX? (Under Windows, the preferred location would be in `%appdata%`).

There are several [configuration directories under my home directory](http://i.imgur.com/cZbHPgA.png).

**Comment by jwbowen** [comment]
I'm still scrounging around for the best (well, the most "Pythonic") way to do this. I might start popping into IRC channels to ask.

**Comment by etiology** [comment]
For OSX I would place it in ```~/Library/Application Support/BuddySuite```

**Comment by biologyguy** [comment]
I'll have time later in the week to figure out exactly what will go in the files again, regardless of where we decide to put them.

**Comment by biologyguy** [comment]
As a related note, the installation will be cleaner if all necessary resources are moved into a clean build directory before running the actual setup script. Otherwise there are a bunch of warnings thrown during install. I'll try to push everything into a temp dir.

**Comment by biologyguy** [comment]
Okay, I think this is all sorted out. I've revamped the installer significantly, including dialog boxes for the user to decide if they want to opt into the data tracking and to provide an email address. It also creates a new directory in the Python modules path (e.g., site-packages), right next to the .egg file. This new buddysuite_data dir is where usage.json and a few other things will live. This seems like a cleaner solution than hard coding a different location for each OS.
Closed with commit 8816f246e19438e12c135fb4c4e5c2322e0deb4f
