### ISSUE TITLE
How does everyone feel about a requirements file?

### ISSUE THREAD

**Issue by etiology** [biologyguy/BuddySuite#59]
I like requirements files.  I think we should make one for this code base using [pip-tools](https://github.com/nvie/pip-tools/).  It handles all of the nitty-gritty parts of external dependencies.  If some requirement changes in one of our main packages, it can update the requirements file.  

Are there any arguments against a requirements file that I should know?

**Comment by jwbowen** [comment]
Not that I'm aware of.

**Comment by biologyguy** [comment]
None that I can think of, but I'm more inclined towards only including actual requirements (e.g., biopython) as apposed to add-ons (e.g., BLAST or RAxML).

**Comment by jwbowen** [comment]
What would the purpose of this requirements file be? Am I correct to assume
you're talking about a requirements.txt that one could use with `pip
install -r requirements.txt`?

**Comment by etiology** [comment]
Yeah that was all.  I find it much easier to use software that has these.  It's a much nicer experience as a user to have all of that environment stuff setup in simple command.  I don't like installing requirements individually.

This doesn't address the external software packages like BLAST or RAxML but we can find alternatives for these.  What about a ```--requirements``` flag that just prints out the require software you need with either a green check mark √ or a red X?

**Comment by jwbowen** [comment]
The setup.py script installs the Python dependencies (biopython, dendropy,
and ete3) from PyPI.

**Comment by biologyguy** [comment]
That was sort of my feeling too, which makes requirements.txt redundant. Unless there's a reason to maintain redundancy?

**Comment by etiology** [comment]
Good points.  It would be redundant.  It's mostly a stylistic choice.  If it's ok I'll mark this closed.
