### ISSUE TITLE
SB prosite_scan and cd_hit functions break alphabetic order

### ISSUE THREAD

**Issue by KarlKeat** [biologyguy/BuddySuite#64]
All of the functions are in alphabetic order except for these.

**Comment by KarlKeat** [comment]
cd_hit hasn't actually been implemented yet, but we can definitely add alpha-order to prosite_scan. You mean the features list, right?

**Comment by biologyguy** [comment]
cd_hit hasn't actually been implemented yet, but we can definitely add alpha-order to prosite_scan. You mean the features list, right?

**Comment by biologyguy** [comment]
I misunderstood your comment. Now I understand, and have resolved it with commit 4c6b85114c50209786104fe76290fed39960e99e
