### ISSUE TITLE
Unknown Blast binaries and zips in codebase

### ISSUE THREAD

**Issue by Cabalist** [biologyguy/BuddySuite#66]
There are a bunch of binaries for Blast in the ```build_dir``` without versions or MD5.  They don't have any version number and they are for a bunch (but not all) architectures.  Why are they being partially mirrored here?  Wouldn't it be easier to include a link (or a script) that downloads the correct version/architecture for the user's system?  At the very least that way MD5 hashes could be verified.

They are also present in the ```develop``` branch which looks to be more current.   

Would you accept a Pull Request with a modified install script?

**Comment by biologyguy** [comment]
Thanks for the comments. We are actually in the process of removing these from the repo; it's not quite as simple as just modifying the install script, however, they will be removed within the week. I absolutely do not want to discourage contribution, but the next few days would be a slightly awkward time to jump on board. If you check back in next Monday, we will have finished a complete overhaul of the unit tests and updated the [developers wiki](https://github.com/biologyguy/BuddySuite/wiki/Developers) to explain how to get the dev environment set up. I'll leave this issue open for now as extra motivation to clean up the blast bins.

**Comment by biologyguy** [comment]
Resolved with commit c195f7ee2aba893af638c8c86d9558f11f731259
