### ISSUE TITLE
Link to MEME suite in SB Purge page is dead

### ISSUE THREAD

**Issue by KarlKeat** [biologyguy/BuddySuite#67]
https://github.com/biologyguy/BuddySuite/wiki/SB-Purge
The site seems to have been moved. The link does not lead anywhere.

**Comment by jwbowen** [comment]
That link works for me: http://i.imgur.com/ynCAdyq.png

**Comment by KarlKeat** [comment]
Sorry, to clarify, the link on that page is dead. 

http://meme.nbcr.net/meme/doc/purge.html

**Comment by jwbowen** [comment]
Ah. I just clicked the link in the email notification and didn't read the title of the issue.

Going to http://nbcr.net/ redirects to http://nbcr.ucsd.edu/. Going to Products > MEME shows this page http://nbcr-222.ucsd.edu/meme.html about the server moving.

The documentation for the purge tool is now here: http://meme-suite.org/doc/purge.html

**Comment by jwbowen** [comment]
I've updated the wiki page with the new link.
