### ISSUE TITLE
Feature requests for V 1.3

### ISSUE THREAD

**Issue by biologyguy** [biologyguy/BuddySuite#68]
All of these feature requests have been separated out into their own issues.

**Comment by KarlKeat** [comment]
Use streams instead of storing everything in RAM?

**Comment by KarlKeat** [comment]
Have DBBuddy warn user about writing summaries instead of sequence
Have DBBuddy set sequence IDs as a human-readable name

**Comment by KarlKeat** [comment]
Stop building mega-strings (using +=) because they are super slow with large output and suck up memory.

**Comment by KarlKeat** [comment]
Make the find_* methods return a start-end pair instead of just a start

**Comment by KarlKeat** [comment]
Maybe add support for calling alignment/tree-inference web servers to align/phylobuddy

**Comment by KarlKeat** [comment]
CSV input? (low priority)

**Comment by KarlKeat** [comment]
Add option to toggle between nexus interleave and sequential (low priority)
