### ISSUE TITLE
combining seqbuddy -dm and -cs command line options

### ISSUE THREAD

**Issue by sellisd** [biologyguy/BuddySuite#84]
It is not clear if it is possible to combine multiple command line options:
e.g. **`test.fa`**
```
>header meta-data
a-c-t-g
```
this works:
`seqbuddy test.fa -dm| seqbuddy -cs`
```
>header
actg
```
but this doesn't:
`seqbuddy test.fa -dm -cs`
```
>header meta-data
actg
```

**Comment by biologyguy** [comment]
Ya, you can only do one at a time, separated by a pipe.
